import time, os

### GLOBAL VARIABLES ###
global_sleep_time = 2 # The amount of seconds the error text will show on a menu, before continuing the loop.
###  END OF GLOBALS  ###

def init_menu_main():
    return_data: tuple
    while True:
        os.system("cls" if os.name == 'nt' else 'clear') # Select the correct way to clear a screen, based on OS
        
        print("Welcome to Steam Detective\nTo start, select one of the options below.")
        print('''Are you entering a Custom Steam ID or a Profile ID
                
                A Custom Steam ID, is one a user has created themselves.
                A Profile ID is a random set of numbers, generated by Valve when a user creates their Steam account.

                1. Custom Steam ID
                2. Profile ID
                0. Exit
            ''')
    
        choice = input("Please select an option: ")

        if not choice.isnumeric():
            print("Your option should only be a number, please try again.")
            time.sleep(global_sleep_time)
            continue

        if int(choice) == 1:
            return_data = init_menu_custom_id()
            break
        elif int(choice) == 2:
            return_data = init_menu_profile_id()
            break
        elif int(choice) == 0:
            return exit()
            break
        else:
            print(f"'{choice}' isn't a valid option, please try again.")
            time.sleep(global_sleep_time)
            continue

    return return_data

def init_menu_custom_id():
    while True:
        os.system("cls" if os.name == 'nt' else 'clear') # Select the correct way to clear a screen, based on OS
        print("You have selected to use a Custom Steam ID, if this is wrong please go back.\nOtherwise please enter the Custom Steam ID\n0. Back")
        choice = input("Enter Custom Steam ID: ")

        if choice == "0" or choice == 0:
            init_menu_main()
            break
        
        if choice == "":
            print("Please enter the Steam ID, before pressing enter.")
            time.sleep(global_sleep_time)
            continue

        return (choice, True)

def init_menu_profile_id():
        while True:
            os.system("cls" if os.name == 'nt' else 'clear') # Select the correct way to clear a screen, based on OS
            print("You have selected to use a Profile ID, if this is wrong please go back.\nOtherwise please enter the ID\n0. Back")
            choice = input("Enter Profile ID: ")

            if choice == "0" or choice == 0:
                init_menu_main()
                break
            
            if not choice.isnumeric():
                print("A Profile ID cannot contain any non-number characters, please try again.")
                time.sleep(global_sleep_time)
                continue

            return (choice, False)